---
- hosts: 10.87.3.47
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: hariapp
        image: "bijuvinoth/javawebapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8888:8080
